# Generated by Django 4.2.20 on 2025-03-22 06:35

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='', validators=[file_upload.models.file_size]),
        ),
    ]
